version: 1.0.{build}
image: Visual Studio 2022

branches:
  only:
    - main
    - dev

environment:
  SONARQUBE_SCANNER_MSBUILD_VERSION: 5.2.1

install:
  - choco install unity --version=2022.3.18 -y

before_build:
  - dotnet tool install --global dotnet-sonarscanner

build_script:
    #- dir "C:\Program Files\Unity.exe" /s /b
  - set PATH=%PATH%;C:\Program Files\Unity 2022.3.18f1\Editor

  # Build your Unity project
  - Unity -serial %UNITY_SERIAL% -username %UNITY_USER_ID% -password %UNITY_USER_PASSWORD% -quit -batchmode -nographics -projectPath C:\projects\solar-system-simulator\ -executeMethod UnityEditor.SyncVS.SyncSolution

  - set JAVA_HOME=C:\Program Files\Java\jdk17
  - set PATH=%JAVA_HOME%\bin;%PATH%

  # Run SonarQube analysis specifying the project file
  - dotnet sonarscanner begin /k:"Solar-System-Simulator" /d:sonar.host.url="http://160.85.252.39:9000" /d:sonar.token="sqp_f5bd91144b884f4a4df8d1f5847011041182a615" /d:sonar.cs.vs.solution.file="C:\projects\solar-system-simulator\Assembly-CSharp.csproj"
  - dotnet build C:\projects\solar-system-simulator\Assembly-CSharp.csproj
  - dotnet sonarscanner end /d:sonar.token="sqp_f5bd91144b884f4a4df8d1f5847011041182a615"

on_finish:
  - Unity -batchmode -returnlicense

artifacts:
  - path: 'Builds/Windows'
    name: WindowsBuild