version: 1.0.{build}
image: Visual Studio 2019

environment:
  SONARQUBE_SCANNER_MSBUILD_VERSION: 5.2.1

before_build:
  - dotnet tool install --global dotnet-sonarscanner

build_script:
  # Run SonarQube analysis
  - dotnet sonarscanner begin /k:"Solar-System-Simulator" /d:sonar.host.url="http://160.85.252.80:9000"  /d:sonar.token="sqp_d7e68db7534040b2ecb26c4d2902fda53b63df67"
  - dotnet build C:\projects\solar-system-simulator
  - dotnet sonarscanner end /d:sonar.token="sqp_d7e68db7534040b2ecb26c4d2902fda53b63df67"

artifacts:
  - path: 'Builds/Windows'
    name: WindowsBuild
